# This file has been generated by mvnix 0.1.0. Configure the build here!
{
  pkgs ? import ((import <nixpkgs> {}).fetchFromGitHub {
    owner   = "nixos";
    repo    = "nixpkgs";
    rev     = "61deecdc34fc609d0f805b434101f3c8ae3b807a"; # 18.09-beta
    sha256  = "147xyn8brvkfgz1z3jbk13w00h6camnf6z0bz0r21g9pn1vv7sb0";
  }) {},
  mavenix ? pkgs.callPackage (import ./mavenix.nix) {},
  doCheck ? false,
}: with pkgs;

let
  gitignore = import (fetchFromGitHub {
    owner   = "siers";
    repo    = "nix-gitignore";
    rev     = "7a2a637fa4a753a9ca11f60eab52b35241ee3c2f";
    sha256  = "0hrins85jz521nikmrmsgrz8nqawj52j6abxfcwjy38rqixcw8y1";
  }) { inherit lib; };
in mavenix {
  inherit doCheck;

  src         = gitignore.gitignoreSource ../.;
  name        = "k";
  infoFile    = ./mavenix-info.json;
  buildInputs = [ git makeWrapper ];

  # dependencies not declared in the POMs
  deps = [
    {
      path = "org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4.jar";
      sha1 = "s0xw0c4d71qh8jgy1jipy385jzihx766";
    }
    {
      path = "org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4.pom";
      sha1 = "nx34986x5284ggylf3bg8yd36hilsn5i";
    }
  ];

  remotes = {
    "central" = "https://repo.maven.apache.org/maven2";
    "runtime.verification" = "https://s3.amazonaws.com/repo.runtime.verification/repository/internal";
    "runtime.verification.snapshots" = "https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots";
  };

  postInstall = ''
    cp -r k-distribution/target/release/k/{bin,include,lib} $out/

    for prog in $out/bin/*; do
      wrapProgram $prog \
        --prefix PATH : ${lib.makeBinPath [
          flex z3 gmp mpfr pkgconfig python3 opam ocaml ocamlPackages.findlib
        ]}
    done
  '';
}
