# This file has been generated by mvnix 0.1.0. Configure the build here!
{
  pkgs ? import ((import <nixpkgs> {}).fetchFromGitHub {
    owner   = "nixos";
    repo    = "nixpkgs";
    rev     = "61deecdc34fc609d0f805b434101f3c8ae3b807a"; # 18.09-beta
    sha256  = "147xyn8brvkfgz1z3jbk13w00h6camnf6z0bz0r21g9pn1vv7sb0";
  }) {},
  mavenix ? pkgs.callPackage (import ./mavenix.nix) {},
  doCheck ? false,
}: with pkgs;

let
  gitignore = callPackage (fetchFromGitHub {
    owner   = "siers";
    repo    = "nix-gitignore";
    rev     = "221d4aea15b4b7cc957977867fd1075b279837b3";
    sha256  = "0xgxzjazb6qzn9y27b2srsp2h9pndjh3zjpbxpmhz0awdi7h8y9m";
  }) { };
in mavenix {
  inherit doCheck;

  src         = gitignore.gitignoreSource [] ../.;
  name        = "k";
  infoFile    = ./mavenix-info.json;
  buildInputs = [ git makeWrapper ];

  # dependencies not declared in the POMs
  deps = [
    {
      path = "org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4.jar";
      sha1 = "s0xw0c4d71qh8jgy1jipy385jzihx766";
    }
    {
      path = "org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4.pom";
      sha1 = "nx34986x5284ggylf3bg8yd36hilsn5i";
    }
  ];

  remotes = {
    "central" = "https://repo.maven.apache.org/maven2";
    "runtime.verification" = "https://s3.amazonaws.com/repo.runtime.verification/repository/internal";
    "runtime.verification.snapshots" = "https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots";
  };

  postPatch = ''
    for file in k-distribution/src/main/scripts/{bin,lib}/*; do
      [ -f $file ] && substituteInPlace $file \
        --replace "/usr/bin/env sh"   ${bash}/bin/sh \
        --replace "/usr/bin/env bash" ${bash}/bin/bash
    done
  '';

  postInstall = ''
    cp -r k-distribution/target/release/k/{bin,include,lib} $out/

    for prog in $out/bin/*; do
      wrapProgram $prog \
        --prefix PATH : ${lib.makeBinPath [
          flex z3 gmp mpfr pkgconfig python3 opam ocaml ocamlPackages.findlib
        ]}
    done
  '';
}
