# This file has been generated by mvnix 0.1.0. Configure the build here!
{ pkgs ? import <nixpkgs> { inherit system; }
, system ? builtins.currentSystem
, mavenix ? pkgs.callPackage (import ./mavenix.nix) {}
, src ? builtins.filterSource (path: type: baseNameOf != "target") ../.
, doCheck ? false
}: with pkgs; mavenix {
  inherit doCheck src;
  name = "k";
  infoFile = ./mavenix-info.json;
  buildInputs = [ git makeWrapper ];
  deps = [
    { "path"="org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4.jar";
      "sha1"="s0xw0c4d71qh8jgy1jipy385jzihx766"; }
    { "path"="org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4.pom";
      "sha1"="nx34986x5284ggylf3bg8yd36hilsn5i"; }
  ];
  remotes = {
    "central" = "https://repo.maven.apache.org/maven2";
    "runtime.verification" = "https://s3.amazonaws.com/repo.runtime.verification/repository/internal";
    "runtime.verification.snapshots" = "https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots";
  };
  postInstall = ''
    cp -r k-distribution/target/release/k/{bin,include,lib} $out/
    for prog in $out/bin/*; do
      wrapProgram $prog \
        --prefix PATH : ${lib.makeBinPath [
          flex z3 gmp mpfr pkgconfig python3 opam ocaml ocamlPackages.findlib
        ]}
    done
  '';
}
